version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd food-delivery
      - npm install

  build:
    commands:
      - echo "Starting build..."
      - npm run build || { echo "Build failed"; exit 1; }

artifacts:
  files:
    - '**/*'
  base-directory: food-delivery/dist