version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd food-delivery
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: food-delivery/dist